version: '3'
services:
  web:
    build: .
    links:
      - chrome
  chrome:
    image: "zenika/alpine-chrome"
    command: --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
